# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: null
backup_email_from: null
backup_email_to: null
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod: 15.skoll.online
domains_test: test-15.skoll.online
gitlab_url: null
odoo_dbfilter: ^15.skoll.online
odoo_initial_lang: en_US
odoo_listdb: true
odoo_oci_image: null
odoo_proxy: null
odoo_version: 15.0
paths_without_crawlers:
- /web
- /website/info
postgres_cidr_whitelist: null
postgres_dbname: 15.skoll.online
postgres_exposed: false
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: '13'
project_author: mario
project_license: no_license
project_name: odoo15
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null
smtp_relay_version: '10'
